const dataSeed = [
    {
        nama: "Kristiadi Eko Sihprianto",
        foto: "https://drive.google.com/open?id=1d2GyqUTJnJ2T2um1HVEmkooXt_m6Szds",
        kepalaKeluarga: "Iman Santosa AS",
        tanggalLahir: "17/12/1994",
        jenisKelamin: "Laki laki",
        wa: "087874878006",
        wilayah: "Paragulan",
        alamat: "Rahasia",
        instagram: "Krisbersemangat",
        kesibukan: "Sudah bekerja",
        bidang: "Creative and brand",
        minatHobi: ["Game", "Desain", "Traveling"],
        tahunSidi: "2011-07-23",
    },
    {
        nama: "Thomas Eko Prihanto",
        foto: "https://drive.google.com/open?id=1HgwO8eEdo4gSwCw0EHlZ_DIp0KVbkcOF",
        kepalaKeluarga: "Sudarto",
        tanggalLahir: "22/01/1995",
        jenisKelamin: "Laki laki",
        wa: "087786862806",
        wilayah: "Paseltan",
        alamat: "Jl. Aselih RT.09/01 No.118 Cipedak, Jagakarsa, Jaksel ",
        instagram: "Toms_ekp",
        kesibukan: "Sudah bekerja",
        bidang: "Pemasaran ",
        minatHobi: ["Musik", "Traveling"],
        tahunSidi: "2011-07-23",
    },
    {
        nama: "Valerian Edsel putra ",
        foto: "https://drive.google.com/open?id=1Fo71Q6zQN9v4MEQTmoAj0uz2k8AzOg2n",
        kepalaKeluarga: "Johan passagi",
        tanggalLahir: "24/07/2022",
        jenisKelamin: "Laki laki",
        wa: "0895410665675",
        wilayah: "Paragulan",
        alamat: "Jln Kebagusan II",
        instagram: "valerriian",
        kesibukan: "Pelajar",
        bidang: "IPS",
        minatHobi: ["Game"],
        tahunSidi: "Belum Sidi",
    },
    {
        nama: "Samuel J R Delhaye",
        foto: "https://drive.google.com/open?id=1rtGcukqcjsBE8Hl_mlA_SMbRUtskjRRo",
        kepalaKeluarga: "Steven Delhaye",
        tanggalLahir: "08/10/1999",
        jenisKelamin: "Laki laki",
        wa: "087889432831",
        wilayah: "Pasutra",
        alamat: "Kalibata",
        instagram: "@samrudolff",
        kesibukan: "Mahasiswa",
        bidang: "Jurusan sistem komputer",
        minatHobi: ["Musik", "Game"],
        tahunSidi: "Sudah sidi",
    },
    {
        nama: "Andhika Putra",
        foto: "https://drive.google.com/open?id=1xHXtZCiPmO-EuWOnI8V00xnl9B8-jtYi",
        kepalaKeluarga: "Johan Pasagi",
        tanggalLahir: "26/01/2000",
        jenisKelamin: "Laki laki",
        wa: "081280304157",
        wilayah: "Paragulan",
        alamat: "Jl kebagusan II No c1 komplek bkkbn pasar minggu jakarta selatan",
        instagram: "andhika_puth",
        kesibukan: "Mahasiswa",
        bidang: "Jurusan teknologi informasi",
        minatHobi: ["Game", "Desain"],
        tahunSidi: "Sudah sidi",
    },
    {
        nama: "Arya Bima Kusuma",
        foto: "https://drive.google.com/open?id=1mh-PrrF-c6myINQP190tPTzPQC_tqPeJ",
        kepalaKeluarga: "Gigih Prihakuntanto",
        tanggalLahir: "03/07/2007",
        jenisKelamin: "Laki laki",
        wa: "0895323015271",
        wilayah: "Paragulan",
        alamat: "Jl. Anggrek no 66, Jagakarsa,Jakarta Selatan, RT01/RW02",
        instagram: "bimbima0",
        kesibukan: "Pelajar",
        bidang: "IPS",
        minatHobi: ["Musik"],
        tahunSidi: "Belum Sidi",
    },
    {
        nama: "Divo Abelardo Benedict",
        foto: "https://drive.google.com/open?id=1iYYaRhOKw0DrP5LyPqXz6Asw6bMYD2aT",
        kepalaKeluarga: "Widijanto Prijosanjoto",
        tanggalLahir: "15/12/2006",
        jenisKelamin: "Laki laki",
        wa: "08111512063",
        wilayah: "Pasutra",
        alamat: "Komp. Perikanan, jl batu 1, no A1 Pejaten timur, pasar minggu",
        instagram: "divo.benedict",
        kesibukan: "Pelajar",
        bidang: "Mipa",
        minatHobi: ["Game"],
        tahunSidi: "Belum Sidi",
    },
    {
        nama: "Yordan Pangestu Gusti ",
        foto: "https://drive.google.com/open?id=1pzqDLc06NmCs9InntZ7UVOYV_pJ4GyoI",
        kepalaKeluarga: "Bapak Bambang Soelistijono ",
        tanggalLahir: "10/07/2007",
        jenisKelamin: "Laki laki",
        wa: "081319066119",
        wilayah: "Destara",
        alamat: "Jalan villa kalisari 2 blok D3",
        instagram: "@odanpg",
        kesibukan: "Pelajar",
        bidang: "Tidak ada jurusan (kurikulum merdeka)",
        minatHobi: ["Game"],
        tahunSidi: "Belum Sidi",
    },
    {
        nama: "Dyandra Nostalia",
        foto: "https://drive.google.com/open?id=1_P7sp7s8h6ahnJq8xDkh0lb6z09DAmbB",
        kepalaKeluarga: "Geger Suprapto",
        tanggalLahir: "19/05/1994",
        jenisKelamin: "Perempuan",
        wa: "085718814407",
        wilayah: "Paseltan",
        alamat: "Jl. Kebembem 1a No.60 Jagakarsa JakSel",
        instagram: "dyandranostalia",
        kesibukan: "Sudah bekerja",
        bidang: "Bekerja, Accounting",
        minatHobi: ["Traveling"],
        tahunSidi: "Sudah sidi",
    },
    {
        nama: "Debora Octarina Putri ",
        foto: "https://drive.google.com/open?id=1OWJ21KVBKonof5LkF8zwlqaT7Z_mTaH0",
        kepalaKeluarga: "Simon ",
        tanggalLahir: "24/07/2022",
        jenisKelamin: "Perempuan",
        wa: "085772666833",
        wilayah: "Paragulan",
        alamat: "Jln.Cilandak KKO, Gg. Hidayah rt 9 rw 8, no 17b",
        instagram: "deboraoctarina",
        kesibukan: "Pelajar",
        bidang: "Akuntansi",
        minatHobi: ["Musik", "Tarik suara", "Drawing"],
        tahunSidi: "Belum Sidi",
    },
    {
        nama: "Andreas Shanada Ariaji",
        foto: "https://drive.google.com/open?id=15uAmYdZ3mzOcaCi1cUtKBplOpm5i1kt-",
        kepalaKeluarga: "Irwan Martono",
        tanggalLahir: "01/09/1999",
        jenisKelamin: "Laki laki",
        wa: "0895353308680",
        wilayah: "Pasutra",
        alamat: "Jl. Ikhlas No.79 RT.04 RW.11 Kec.Beji Kel.Tanah Baru Depok (Rumah Asri B)",
        instagram: "andreashanada",
        kesibukan: "Mahasiswa",
        bidang: "Kuliah",
        minatHobi: ["Musik"],
        tahunSidi: "Sudah sidi",
    },
    {
        nama: "Dilbert Prasetyo Adhi",
        foto: "https://drive.google.com/open?id=1wp4SdSdJmvkB6midnppGh6JVb1Fn2v3t",
        kepalaKeluarga: "geger suprapto",
        tanggalLahir: "11/11/2008",
        jenisKelamin: "Laki laki",
        wa: "082122415997",
        wilayah: "Paseltan",
        alamat: "jl.kebembem 1a no.60",
        instagram: "Zamnnn",
        kesibukan: "Pelajar",
        bidang: "pelajar (smp)",
        minatHobi: ["Game"],
        tahunSidi: "Belum Sidi",
    },
    {
        nama: "Edgar Timothy Parikesit ",
        foto: "https://drive.google.com/open?id=17HPpI2RW2LSNV0fdPUSyRAq6rf1xJfrV",
        kepalaKeluarga: "Firman Eberth Parikesit",
        tanggalLahir: "26/12/2006",
        jenisKelamin: "Laki laki",
        wa: "08118454998",
        wilayah: "Lainnya",
        alamat: "Jl. Joe Kelapa Tiga d' menteng Residence no.2 RT07/06 Lenteng Agung, Jakarta Selatan",
        instagram: "@edgartimothy.p",
        kesibukan: "Pelajar",
        bidang: "Pelajar, Kurikulum Merdeka",
        minatHobi: ["Game", "Traveling", "Menulis"],
        tahunSidi: "Belum Sidi",
    },
    {
        nama: "Edna Jasmine Parikesit ",
        foto: "https://drive.google.com/open?id=1J5ZNd112vqgiDywt1c_OFFU5T43qU9mg",
        kepalaKeluarga: "Firman Eberth Parikesit",
        tanggalLahir: "13/07/2005",
        jenisKelamin: "Perempuan",
        wa: "08111354889",
        wilayah: "Lainnya",
        alamat: "D'menteng Recidence no 2",
        instagram: "@awomm_",
        kesibukan: "Pelajar",
        bidang: "Pelajar SMA, jurusan IPA ",
        minatHobi: ["Musik", "Game", "Desain", "Menggambar"],
        tahunSidi: "Belum Sidi",
    },
    {
        nama: "Kevin Kristian",
        foto: "https://drive.google.com/open?id=1u4HR3ai8_A7gXj6FhSWjjE6bTaCUk-Of",
        kepalaKeluarga: "Suseno W",
        tanggalLahir: "21/05/1995",
        jenisKelamin: "Laki laki",
        wa: "085780777930",
        wilayah: "Destara",
        alamat: "Cimanggis, Depok",
        instagram: "kvkristian",
        kesibukan: "Sudah bekerja",
        bidang: "IT",
        minatHobi: ["Game"],
        tahunSidi: "Sudah sidi",
    },
    {
        nama: "Jesaya Ayodya Kamajaya ",
        foto: "https://drive.google.com/open?id=1SLPwrFaV-BR9hcI2iTSin5uCGZIGzXJH",
        kepalaKeluarga: "Joko Susilo ",
        tanggalLahir: "25/04/2006",
        jenisKelamin: "Laki laki",
        wa: "081381104711",
        wilayah: "Paseltan",
        alamat: "jalan persahabatan 2 no 103B ",
        instagram: "@jesaya_43",
        kesibukan: "Pelajar",
        bidang: "pelajar smk, multimedia\n",
        minatHobi: ["Musik", "Game", "Desain"],
        tahunSidi: "Belum Sidi",
    },
    {
        nama: "Richie Ray Mangundap",
        foto: "https://drive.google.com/open?id=1HlhIh1ir-IzSpbYWlPCZLQnO8yxi43CL",
        kepalaKeluarga: "Suseno Widyonarko",
        tanggalLahir: "23/10/2005",
        jenisKelamin: "Laki laki",
        wa: "+62 857-7507-1433",
        wilayah: "Destara",
        alamat: "Komp. Griya tugu asri c4/10 tugu, cimanggis,depok, Jawa barat, Indonesia rt/rw : 3/19",
        instagram: "Richieeraym",
        kesibukan: "Pelajar",
        bidang: "Tentang dunia percetakan grafika",
        minatHobi: ["Musik", "Game", "Basket", "voli"],
        tahunSidi: "Belum Sidi",
    },
    {
        nama: "Vifo rezaldi yoga pratama",
        foto: "https://drive.google.com/open?id=1mpXithgO9iceM1WJHQFObMIljB0hCrl_",
        kepalaKeluarga: "Purwanto",
        tanggalLahir: "04/04/1997",
        jenisKelamin: "Laki laki",
        wa: "085772486978",
        wilayah: "Paragulan",
        alamat: "Jatipadang",
        instagram: "@mas.vifoo",
        kesibukan: "Sudah bekerja",
        bidang: "Organisasi dan musik",
        minatHobi: ["Musik", "Organisasi"],
        tahunSidi: "Sudah sidi",
    },
    {
        nama: "Gabriela Tabitha Yahya ",
        foto: "https://drive.google.com/open?id=1gqSdXwoBc_yONCfbEeYF1ItjEmAg5KuB",
        kepalaKeluarga: "Benyamin yahya",
        tanggalLahir: "25/05/2022",
        jenisKelamin: "Perempuan",
        wa: "081384659463",
        wilayah: "Paseltan",
        alamat: "Kebagusan kecil RT 14 RW 03",
        instagram: "jyunghyn._",
        kesibukan: "Pelajar",
        bidang: "bernyanyi ",
        minatHobi: ["Tarik suara"],
        tahunSidi: "Belum Sidi",
    },
    {
        nama: "Priscilla Anastasia Delhaye",
        foto: "https://drive.google.com/open?id=1N-W6RxoGjGvRsp_7K5rr52aWAw06R4UA",
        kepalaKeluarga: "Steven Delhaye",
        tanggalLahir: "27/04/1996",
        jenisKelamin: "Perempuan",
        wa: "087880215477",
        wilayah: "Pasutra",
        alamat: "Apartment Kalibata City, Borneo Tower",
        instagram: "@cilladelhaye",
        kesibukan: "Sudah bekerja",
        bidang: "Recruitment (HR)",
        minatHobi: [
            "Tarik suara",
            "Public speaking",
            "Organisasi",
            "Traveling",
            "Fotografi",
            "Konseling",
        ],
        tahunSidi: "Sudah sidi",
    },
    {
        nama: "Nathasya Octava Theoyana",
        foto: "https://drive.google.com/open?id=1jCgWC2NF_GAnq7Om0tEXoEcjiyzJnBfL",
        kepalaKeluarga: "Yohanes warjo",
        tanggalLahir: "31/10/1997",
        jenisKelamin: "Perempuan",
        wa: "081286435250",
        wilayah: "Destara",
        alamat: "Jalan masjid irsyadul ummah ",
        instagram: "@tasyaaoct",
        kesibukan: "Sudah bekerja",
        bidang: "Digital marketing",
        minatHobi: ["Tarik suara", "Public speaking", "Traveling", "Fotografi"],
        tahunSidi: "Sudah sidi",
    },
    {
        nama: "Gita",
        foto: "https://drive.google.com/open?id=1YOG9ps3M1mAjBr0_F8uKxLL_-t2RQ3ew",
        kepalaKeluarga: "Sigit palgunadi",
        tanggalLahir: "18/10/1997",
        jenisKelamin: "Perempuan",
        wa: "081281373989",
        wilayah: "Paragulan",
        alamat: "Jl muara no 33 rt 10 rw 03 tanjung barat jakarta selatan",
        instagram: "florenciagita",
        kesibukan: "Sudah bekerja",
        bidang: "Social media",
        minatHobi: ["Game", "Traveling", "Fotografi"],
        tahunSidi: "Sudah sidi",
    },
    {
        nama: "Wahyu Yuadysan Adittana",
        foto: "https://drive.google.com/open?id=1nJagMcfTQ8Rh-wfX7sI25czsrinWRQ0b",
        kepalaKeluarga: "Budi Santoso",
        tanggalLahir: "04/10/2001",
        jenisKelamin: "Laki laki",
        wa: "081818995833",
        wilayah: "Paseltan",
        alamat: "Jl. Platina II Perum Griya Mellina Blok A2/2 Kel. Curug, Kec. Gunung Sindur, Kab. Bogor, 16340",
        instagram: "dysan_dw",
        kesibukan: "Mahasiswa",
        bidang: "Teknik Industri",
        minatHobi: ["Game"],
        tahunSidi: "Sudah sidi",
    },
    {
        nama: "Cleisya Elaza",
        foto: "https://drive.google.com/open?id=1DYEeQR85_0UWtcF1mHWO8KWYEUiX0CLd",
        kepalaKeluarga: "Arry Putro K",
        tanggalLahir: "22/10/2007",
        jenisKelamin: "Perempuan",
        wa: "081511661632",
        wilayah: "Destara",
        alamat: "Komplek Villa Kalisari, jl.vikas 3, Blok D.12, Pasir Gunung Selatan, Cimanggis, Depok",
        instagram: "clsylzaa",
        kesibukan: "Pelajar",
        bidang: "semua mapel susah",
        minatHobi: ["Musik", "Organisasi", "Traveling"],
        tahunSidi: "Belum Sidi",
    },
    {
        nama: "Kasih",
        foto: "https://drive.google.com/open?id=1u-l8w1_5vCLLm8Cug1IycP4-u-wFZeWz",
        kepalaKeluarga: "Warto",
        tanggalLahir: "30/05/2008",
        jenisKelamin: "Perempuan",
        wa: "085718102512",
        wilayah: "Paseltan",
        alamat: "Kebagusan kecil rt 003 rw 08 no.45",
        instagram: "@laaa_kh",
        kesibukan: "Pelajar",
        bidang: "3 SMP ",
        minatHobi: ["Musik", "Traveling"],
        tahunSidi: "Belum Sidi",
    },
    {
        nama: "ELIEZER ADHIE NUGROHO",
        foto: "https://drive.google.com/open?id=1xhp7E7Bwt6LY4_tnL4ejCL83AXytkqYI",
        kepalaKeluarga: "Ibu Ertiningsih",
        tanggalLahir: "07/01/2007",
        jenisKelamin: "Laki laki",
        wa: "081548134671",
        wilayah: "Paseltan",
        alamat: "Jl Jagakarsa 1 Rt 005 Rw 007 No 4 Kecamatan jagakarsa kelurahan Jagakarsa",
        instagram: "adinugrohoeliezer",
        kesibukan: "Pelajar",
        bidang: "Pelajar Teknik Grafika",
        minatHobi: ["Game", "Traveling"],
        tahunSidi: "Belum Sidi",
    },
    {
        nama: "Ester Christihappy",
        foto: "https://drive.google.com/open?id=1rKtA5Czw0BPu441BN59EhgLWwxGa0BBQ",
        kepalaKeluarga: "Ricky Wattimena",
        tanggalLahir: "01/10/1994",
        jenisKelamin: "Perempuan",
        wa: "081294659635",
        wilayah: "Pandur",
        alamat: "Jl. Cikoko barat IV No.27 rt.03/rw.05 Pancoran, Jakarta Selatan 12770",
        instagram: "@christihappy",
        kesibukan: "Sudah bekerja",
        bidang: "Kedokteran gigi",
        minatHobi: ["Musik", "Tarik suara", "Traveling"],
        tahunSidi: "Sudah sidi",
    },
    {
        nama: "Arleta Ivana Nuki Tunggadewi ",
        foto: "https://drive.google.com/open?id=1Oc9zrFbCZfy9bUfoYf7ytevpNyw6FMBs",
        kepalaKeluarga: "Wisnu Triaji",
        tanggalLahir: "19/12/2009",
        jenisKelamin: "Perempuan",
        wa: "08119741912",
        wilayah: "Pasutra",
        alamat: "Jl. Kalibata Selatan No. 38 RT 01 RW 04",
        instagram: "@.arletaivanaa",
        kesibukan: "Pelajar",
        bidang: "Pelajar Smp",
        minatHobi: ["Musik", "Traveling", "Menulis"],
        tahunSidi: "Belum Sidi",
    },
    {
        nama: "Cornelius Indra Hengkengbala",
        foto: "https://drive.google.com/open?id=1-qxuPh9fiQJHTqefid44vkfBE7kuF1RM",
        kepalaKeluarga: "Yoseph L. Hengkengbala",
        tanggalLahir: "30/10/1996",
        jenisKelamin: "Laki laki",
        wa: "081911718889",
        wilayah: "Lainnya",
        alamat: "Komplek Buncit Indah, mimosa V, B14",
        instagram: "indra.cornelius",
        kesibukan: "Sudah bekerja",
        bidang: "",
        minatHobi: ["Musik"],
        tahunSidi: "Sudah sidi",
    },
    {
        nama: "Amadeus Janaesta",
        foto: "https://drive.google.com/open?id=1sQzEI76YlMHr-nFQ6JCmbyV6YUD_Dja0",
        kepalaKeluarga: "Paulus Suharman",
        tanggalLahir: "08/05/2006",
        jenisKelamin: "Laki laki",
        wa: "081211892717",
        wilayah: "Paseltan",
        alamat: "Jl. Wira no. 29 rt. 002/015 kel. Srengsengsawah kec. Jagakarsa jakarta selatan",
        instagram: "@amadeusjnsth",
        kesibukan: "Pelajar",
        bidang: "Jurusan IPS",
        minatHobi: ["Game"],
        tahunSidi: "Belum Sidi",
    },
    {
        nama: "Artyasti Elata ( ove )",
        foto: "https://drive.google.com/open?id=1nP3VhN0WbDk-CUws-uZrz0BxTmOA__QU",
        kepalaKeluarga: "Arie Prawesti",
        tanggalLahir: "15/11/2008",
        jenisKelamin: "Perempuan",
        wa: "08122229175",
        wilayah: "Paragulan",
        alamat: "Perumahan Pondok Sukahati Indah - Cibinong",
        instagram: "@tyartyaa_",
        kesibukan: "Pelajar",
        bidang: "Semua mapel",
        minatHobi: [
            "Musik",
            "Tarik suara",
            "Public speaking",
            "Desain",
            "Organisasi",
            "Fotografi",
        ],
        tahunSidi: "Belum Sidi",
    },
    {
        nama: "Damar Dwi Nugroho ",
        foto: "https://drive.google.com/open?id=1W0Az2g5F2-7pWqyiXh9ZnHTyUlxtbvwl",
        kepalaKeluarga: "Raden Sutopo",
        tanggalLahir: "29/07/2004",
        jenisKelamin: "Laki laki",
        wa: "085715878883",
        wilayah: "Paragulan",
        alamat: "Jl. Jambu II no. 60 Cipedak Jagakarsa Jakarta Selatan ",
        instagram: "damar_290",
        kesibukan: "Tidak berkegiatan ",
        bidang: "Tata boga",
        minatHobi: ["Game", "Fotografi"],
        tahunSidi: "Sudah sidi",
    },
    {
        nama: "Nathanael Nugroho ",
        foto: "https://drive.google.com/open?id=1PiTHAkNGGq-8rkZw7co2Vc1nL1KIXbNc",
        kepalaKeluarga: "Suyadi",
        tanggalLahir: "04/12/2009",
        jenisKelamin: "Laki laki",
        wa: "087723809697",
        wilayah: "Destara",
        alamat: "Jl.Palapa timur no 8",
        instagram: "ngrhooo",
        kesibukan: "Pelajar",
        bidang: "Pelajar",
        minatHobi: ["Musik", "Game"],
        tahunSidi: "Belum Sidi",
    },
    {
        nama: "Ariyoly Christian Putra ",
        foto: "https://drive.google.com/open?id=1KqyAwLLaDQttQqJl7TaRjA4mag6NrIIL",
        kepalaKeluarga: "Soelistyowati ",
        tanggalLahir: "18/10/2004",
        jenisKelamin: "Laki laki",
        wa: "0877-7231-4538",
        wilayah: "Paragulan",
        alamat: "Jl Ampera Raya Gg.Sawo no39",
        instagram: "Akihiko_2418",
        kesibukan: "Pelajar",
        bidang: "Multimedia ",
        minatHobi: ["Desain"],
        tahunSidi: "Sudah sidi",
    },
    {
        nama: "Christiano Michael Moses Kurniawan",
        foto: "https://drive.google.com/open?id=1m4bRlKAZnBqlKPP5IY0DrJgRxr-r9Zh9",
        kepalaKeluarga: "Sunarno",
        tanggalLahir: "26/08/2007",
        jenisKelamin: "Laki laki",
        wa: "081326231371",
        wilayah: "Pandur",
        alamat: "Jln. Raya Citayam Parung, Kp. Ceringin, Rt003/011, No.45, Ragajaya, Bojonggede, Bogor",
        instagram: "sesss.u",
        kesibukan: "Pelajar",
        bidang: "SMP",
        minatHobi: ["Game", "Basket"],
        tahunSidi: "Belum Sidi",
    },
    {
        nama: "Anindya Eliana Manuela Putri",
        foto: "https://drive.google.com/open?id=1DqX92BOjyOrEukKC44R41O4-gcrwla4N",
        kepalaKeluarga: "Handoko",
        tanggalLahir: "20/10/2009",
        jenisKelamin: "Perempuan",
        wa: "+62 813-8307-6017",
        wilayah: "Destara",
        alamat: "Perumahan wartawan purimulya jalan sensor no 1",
        instagram: "Ninin_lianaa",
        kesibukan: "Pelajar",
        bidang: "Pelajar",
        minatHobi: ["Musik", "Game"],
        tahunSidi: "Belum Sidi",
    },
    {
        nama: "Petra passa martono",
        foto: "https://drive.google.com/open?id=1jEv7WW6BrgvYm-3sC3OgmL5f293oZw8S",
        kepalaKeluarga: "Mulyo Martono",
        tanggalLahir: "27/03/2007",
        jenisKelamin: "Laki laki",
        wa: "081383992007",
        wilayah: "Paseltan",
        alamat: "Limus pratama cendana 6 F16 no 20 ",
        instagram: "pet_ro.nas",
        kesibukan: "Pelajar",
        bidang: "SMA ",
        minatHobi: ["Musik", "Public speaking", "Game"],
        tahunSidi: "Belum Sidi",
    },
    {
        nama: "Putra Filemon A.",
        foto: "https://drive.google.com/open?id=1O1wj05ETCN8EuUhgd0dfxlm5wuz1gCZG",
        kepalaKeluarga: "Edy Muryanto",
        tanggalLahir: "14/12/2001",
        jenisKelamin: "Laki laki",
        wa: "087781940080",
        wilayah: "Paseltan",
        alamat: "Srengseng Sawah, Jagakarsa, Jakarya Selatan",
        instagram: "Putrafadinugroho",
        kesibukan: "Mahasiswa",
        bidang: "",
        minatHobi: ["Tarik suara", "Desain"],
        tahunSidi: "Sudah sidi",
    },
    {
        nama: "Felicia Monika",
        foto: "https://drive.google.com/open?id=1cMXeRI-KjaaPV4uG_Zy9REebZr0BgvwD",
        kepalaKeluarga: "",
        tanggalLahir: "13/09/1997",
        jenisKelamin: "Perempuan",
        wa: "082186870930",
        wilayah: "Lainnya",
        alamat: "Jl Baung No 33 Pasar Minggu",
        instagram: "feliciamonika",
        kesibukan: "Sudah bekerja",
        bidang: "",
        minatHobi: ["Musik", "Traveling"],
        tahunSidi: "Sudah sidi",
    },
];
const { MongoClient } = require("mongodb");

const uri =
    "mongodb+srv://admin:kompagkj@cluster0.i8brg.mongodb.net/?retryWrites=true&w=majority";

const client = new MongoClient(uri);
async function mongoSeed() {
    try {
        db = client.db("pemuda");
        const collection = db.collection("pemuda");
        await collection.drop();
        const pemuda = await collection.insertMany(dataSeed);
        console.log(pemuda);
        console.log("berhasil insert data");
    } catch (error) {
        console.log(error);
    }
}

mongoSeed();
